# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2030a5e3935ef8561f2b99d15770b9140fe57626ecd80838d259a3942587485ff22a7a8a26d874e25ab6d680833b7ae60bc78c1422e5ea50a4b8a7b2b02ccf

test:
  secret_key_base: 71b9a11a18ab2e41b3a848b2373a583da9e1477b423f077261f709985823adc85b12ef8e6341088e61f042cc10cd9a06ee19f3ed9bcb51951c82fef000a3d8fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
